routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
   // return view('welcome');
    return view('profesores');
}) -> name('profesores');*/

Route::resource('profesor', "ProfesorController");

Route::get('estudiantes/byProfesor/{idProfesor}', 'EstudianteController@getByProfesor')->name('estudiantesByProfesor');
Route::resource('estudiantes', 'EstudianteController');

/*Route::get('/estudiantes', function () {
     return view('estudiantes');
 }) -> name('estudiantes');*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Estudiante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estudiante extends Model
{
    //Profesor referenciado por el id_profesor
    public function profesor()
    {
        return $this->belongsTo('App\Profesor');
    }
}

app/Http/Controllers/EstudianteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App;

class EstudianteController extends Controller
{

    public function __construct()
    {
        //indica que acceder a las vistas y recursos de este controlador necesitan autenticacion
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estudiantesList = App\Estudiante::paginate(4);
        return view('estudiantes.estudiantes', compact('estudiantesList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $profesorList = App\Profesor::all();
        return view('estudiantes.estudiantes_add', compact('profesorList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $estudiante = new App\Estudiante();
        $estudiante->name = $request->name;
        $estudiante->direccion = $request->direccion;
        $profesorId = $request->input('profesores');
        $estudiante->profesor_id = $profesorId;
        $estudiante->save();
        return redirect()->route('estudiantes.index')->with('mensaje','Estudiante Agregado!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = App\Estudiante::findOrFail($id);
        $profesorList = App\Profesor::all();
        return view('estudiantes.estudiantes_edit', compact('item', 'profesorList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $estudiante = App\Estudiante::findOrFail($id);
        $estudiante->name = $request->name;
        $estudiante->direccion = $request->direccion;
        $profesorId = $request->input('profesores');
        $estudiante->profesor_id = $profesorId;
        $estudiante->save();
        return redirect()->route('estudiantes.index')->with('mensaje','Estudiante editado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estudiante = App\Estudiante::findOrFail($id);
        $estudiante->delete();
        return redirect()->route('estudiantes.index')->with('mensaje','Estudiante eliminado!');
    }

    /**
     * Retorna los estudiantes asignados al profesor
     * **/
    public function getByProfesor($idProfesor){
        $profesor = App\Profesor::find($idProfesor);
        $estudiantesList = $profesor->estudiantes;
        return view('estudiantes.estudiantes_by_profesor', compact('estudiantesList', 'profesor'));
    }
}

resources/views/estudiantes/estudiantes.blade.php
@extends("plantilla")

@section("seccion")
    <h1>Estudiantes</h1>
    @if ( session('mensaje') )
        <div class="alert alert-success">{{ session('mensaje') }}
        <button type="button" class="close" data-dismiss="alert">&times;</button></div>
    @endif
    <a href="{{ route('estudiantes.create') }}">
        <button class="btn btn-primary mb-4">Agregar</button>  
    </a>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Direccion</th>
        <th scope="col">Pofesor</th>
        <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach ($estudiantesList as $item)
        <tr>
        <th scope="row">{{ $item -> id}}</th>
        <td>{{$item -> name}}</td>
        <td>{{$item -> direccion}}</td>
        <td>{{$item -> profesor->name}}</td>
        <td>
            <a href="{{ route('estudiantes.edit', $item) }}"><button class="btn d-inline">Editar</button></a>
            <form action="{{ route('estudiantes.destroy', $item) }}" class="d-inline" method="POST">
                @method('DELETE')
                @csrf
                <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
            </form> 
        </td>
        </tr>
    @endforeach
    </tbody>
    </table>
    {{ $estudiantesList->links() }}
@endsection

resources/views/estudiantes/estudiantes_add.blade.php
@extends("plantilla")

@section("seccion")
    <h1>Crear estudiante</h1>
<form action="{{ route('estudiantes.store') }}" method="POST">
        @csrf
        <input type="text" name="name" placeholder="Nombre" class="form-control mb-4">
        <input type="text" name="direccion" placeholder="Direccion" class="form-control mb-4">
        <label for="profesores">Profesor:</label>
        <select name="profesores" id="profesores" class="form-control mb-4">
            @foreach($profesorList as $profesor )
              <option value="{{ $profesor->id }}">{{ $profesor->name }}</option>
            @endforeach
          </select>
        <button class="btn btn-primary btn-block" type="submit">Agregar</button>
    </form>
@endsection

resources/views/estudiantes/estudiantes_by_profesor.blade.php
@extends("plantilla")

@section("seccion")
    <h2>Estudiantes asignados a:</h2>
    <h1 class="mb-4">{{$profesor->name}}</h1>
    @if ( session('mensaje') )
        <div class="alert alert-success">{{ session('mensaje') }}
        <button type="button" class="close" data-dismiss="alert">&times;</button></div>
    @endif
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Direccion</th>
        <th scope="col">Pofesor</th>
        <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach ($estudiantesList as $item)
        <tr>
        <th scope="row">{{ $item -> id}}</th>
        <td>{{$item -> name}}</td>
        <td>{{$item -> direccion}}</td>
        <td>{{$item -> profesor->name}}</td>
        <td>
            <a href="{{ route('estudiantes.edit', $item) }}"><button class="btn d-inline">Editar</button></a>
            <form action="{{ route('estudiantes.destroy', $item) }}" class="d-inline" method="POST">
                @method('DELETE')
                @csrf
                <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
            </form> 
        </td>
        </tr>
    @endforeach
    </tbody>
    </table>
@endsection

resources/views/estudiantes/estudiantes_edit.blade.php
@extends("plantilla")

@section("seccion")
    <h1>Editar estudiante</h1>
<form action="{{ route('estudiantes.update', $item->id) }}" method="POST">
        @csrf
        @method('PUT')
        <input type="text" name="name" placeholder="Nombre" class="form-control mb-4" value="{{ $item->name}}">
        <input type="text" name="direccion" placeholder="Direccion" class="form-control mb-4" value="{{ $item->direccion}}">
        <select name="profesores" id="profesores" class="form-control mb-4">
            @foreach($profesorList as $profesor )
              <option value="{{ $profesor->id }}"
                {{ ($profesor->id === $item->profesor_id) ? 'selected' : '' }}>{{ $profesor->name }}</option>
            @endforeach
          </select>
        <button class="btn btn-primary btn-block" type="submit">Editar</button>
    </form>
@endsection