routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
   // return view('welcome');
    return view('profesores');
}) -> name('profesores');*/

Route::resource('profesor', "ProfesorController");

Route::get('estudiantes/byProfesor/{idProfesor}', 'EstudianteController@getByProfesor')->name('estudiantesByProfesor');
Route::resource('estudiantes', 'EstudianteController');

/*Route::get('/estudiantes', function () {
     return view('estudiantes');
 }) -> name('estudiantes');*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

resources/views/profesores/profesores.blade.php
@extends("plantilla")

@section("seccion")
    <h1>Profesores</h1>
    @if ( session('mensaje') )
        <div class="alert alert-success">{{ session('mensaje') }}
        <button type="button" class="close" data-dismiss="alert">&times;</button></div>
    @endif
    <a href="{{ route('profesor.create') }}">
        <button class="btn btn-primary mb-4">Agregar</button>  
    </a>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Telefono</th>
        <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach ($profesoresList as $item)
        <tr>
        <th scope="row">{{ $item -> id}}</th>
        <td>{{$item -> name}}</td>
        <td>{{$item -> celphone}}</td>
        <td>
            <a href="{{ route('profesor.edit', $item) }}"><button class="btn d-inline">Editar</button></a>
            <a href="{{ route('estudiantesByProfesor', $item) }}"><button class="btn d-inline">List estudiantes</button></a>
            <form action="{{ route('profesor.destroy', $item) }}" class="d-inline" method="POST">
                @method('DELETE')
                @csrf
                <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
            </form> 
        </td>
        </tr>
    @endforeach
    </tbody>
    </table>
    {{ $profesoresList->links() }}
@endsection

resources/views/profesores/profesores_add.blade.php
@extends("plantilla")

@section("seccion")
    <h1>Crear profesor</h1>
<form action="{{ route('profesor.store') }}" method="POST">
        @csrf
        <input type="text" name="name" placeholder="Nombre" class="form-control mb-4">
        <input type="text" name="celphone" placeholder="Telefono" class="form-control mb-4">
        <button class="btn btn-primary btn-block" type="submit">Agregar</button>
    </form>
@endsection

resources/views/profesores/profesores_edit.blade.php
@extends("plantilla")

@section("seccion")
    <h1>Editar profesor</h1>
<form action="{{ route('profesor.update', $item->id) }}" method="POST">
        @csrf
        @method('PUT')
        <input type="text" name="name" placeholder="Nombre" class="form-control mb-4" value="{{ $item->name }}">
        <input type="text" name="celphone" placeholder="Telefono" class="form-control mb-4" value="{{ $item-> celphone}}">
        <button class="btn btn-primary btn-block" type="submit">Editar</button>
    </form>
@endsection